service: default
runtime: nodejs10
env: standard
env_variables:
  NODE_ENV: production

instance_class: F2
handlers:
  - url: /.*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_instances: 3
network: {}