name: Deploy to gcloud
on: 
  push:
    branches:
      - master

jobs:
  my-job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          DEUS_KEY: ${{ secrets.DEUS_KEY }}

      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy app.yml     
